# Generated by Django 5.2.1 on 2025-07-27 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClothingCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('gender', models.CharField(choices=[('M', 'Men'), ('W', 'Women'), ('K', 'Kids'), ('U', 'Unisex')], max_length=1)),
                ('icon', models.CharField(blank=True, max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='ClothingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('size', models.CharField(choices=[('XS', 'Extra Small'), ('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large'), ('XXL', 'Double Extra Large'), ('XXXL', 'Triple Extra Large')], max_length=4)),
                ('age_group', models.CharField(choices=[('newborn', 'Newborn (0-3 months)'), ('infant', 'Infant (3-12 months)'), ('toddler', 'Toddler (1-5 years)'), ('child', 'Child (5-12 years)'), ('teen', 'Teen (12-17 years)'), ('adult', 'Adult')], max_length=10)),
                ('color', models.CharField(max_length=50)),
                ('material', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=100)),
                ('stock_quantity', models.PositiveIntegerField(default=0)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='clothings.clothingcategory')),
            ],
        ),
        migrations.CreateModel(
            name='ClothingImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='clothing_images/')),
                ('is_main', models.BooleanField(default=False)),
                ('alt_text', models.CharField(blank=True, max_length=100)),
                ('clothing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='clothings.clothingitem')),
            ],
        ),
    ]
