# Generated by Django 5.2.1 on 2025-08-10 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothingitem',
            name='like_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='clothingitem',
            name='share_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
