# Generated by Django 5.2.1 on 2025-09-22 13:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clothings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='clothingitem',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clothes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='clothingitem',
            name='liked_by',
            field=models.ManyToManyField(blank=True, related_name='liked_clothings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='clothingimage',
            name='clothing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='clothings.clothingitem'),
        ),
    ]
