# Generated by Django 5.2.1 on 2025-09-19 22:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothings', '0003_alter_clothingitem_created_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='clothingitem',
            name='liked_by',
            field=models.ManyToManyField(blank=True, related_name='liked_clothings', to=settings.AUTH_USER_MODEL),
        ),
    ]
