# Generated by Django 5.2.1 on 2025-09-22 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('apartment', 'Apartment'), ('detached', 'Detached House'), ('semi-detached', 'Semi-Detached House'), ('terraced', 'Terraced House'), ('bungalow', 'Bungalow'), ('duplex', 'Duplex'), ('villa', 'Villa'), ('studio', 'Studio'), ('other', 'Other')], default='apartment', max_length=20)),
                ('title', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('bedrooms', models.PositiveIntegerField()),
                ('bathrooms', models.PositiveIntegerField()),
                ('area', models.PositiveIntegerField(help_text='Area in square meters')),
                ('description', models.TextField()),
                ('is_featured', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(unique=True)),
                ('like_count', models.PositiveIntegerField(default=0)),
                ('share_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Houses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HouseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('icon', models.CharField(help_text='Font Awesome icon class', max_length=30)),
            ],
            options={
                'verbose_name_plural': 'House Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='HouseImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='house_images/%Y/%m/%d/')),
                ('is_featured', models.BooleanField(default=True)),
                ('alt_text', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name': 'House Image',
                'verbose_name_plural': 'House Images',
            },
        ),
    ]
