# Generated by Django 5.2.1 on 2025-09-19 11:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0005_alter_house_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='liked_by',
            field=models.ManyToManyField(blank=True, related_name='liked_houses', to=settings.AUTH_USER_MODEL),
        ),
    ]
