# Generated by Django 5.2.1 on 2025-06-23 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_item_likes_count_item_shares_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='likes_count',
            new_name='like_count',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='shares_count',
            new_name='share_count',
        ),
    ]
