# Generated by Django 5.2.1 on 2025-07-14 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='category',
            field=models.CharField(choices=[('car', 'Car'), ('truck', 'Truck'), ('motorcycle', 'Motorcycle'), ('bicycle', 'Bicycle'), ('suv', 'SUV'), ('van', 'Van'), ('bus', 'Bus'), ('commercial', 'Commercial Vehicles')], default='car', max_length=20),
        ),
    ]
