# Generated by Django 5.2.1 on 2025-09-19 15:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0006_rename_date_added_vehicle_created_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='liked_by',
            field=models.ManyToManyField(blank=True, related_name='liked_vehicles', to=settings.AUTH_USER_MODEL),
        ),
    ]
