# Generated by Django 5.2.1 on 2025-09-19 18:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electronics', '0005_product_is_featured'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='liked_by',
            field=models.ManyToManyField(blank=True, related_name='liked_electronics', to=settings.AUTH_USER_MODEL),
        ),
    ]
