# Generated by Django 5.2.1 on 2025-07-27 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('conversation', '0001_initial'),
        ('poultryitems', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='poultryitems.item'),
        ),
    ]
