# Generated by Django 5.2.1 on 2025-09-22 13:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=110, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='ChickenSeller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farm_name', models.CharField(max_length=200, verbose_name='Farm Name')),
                ('location', models.CharField(max_length=100, verbose_name='Location')),
                ('available_quantity', models.PositiveIntegerField(verbose_name='Available Chickens')),
                ('min_price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Minimum Price')),
                ('max_price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Maximum Price')),
                ('breeds', models.CharField(max_length=300, verbose_name='Breeds')),
                ('description', models.TextField(verbose_name='Description')),
                ('delivery_available', models.BooleanField(default=False, verbose_name='Delivery Available')),
                ('vaccinated', models.BooleanField(default=False, verbose_name='Vaccinated')),
                ('contact_number', models.CharField(max_length=20, verbose_name='Contact Number')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('facebook_url', models.URLField(blank=True, null=True, verbose_name='Facebook URL')),
                ('telegram_handle', models.CharField(blank=True, max_length=100, null=True, verbose_name='Telegram Handle')),
                ('whatsapp_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='WhatsApp Number')),
                ('instagram_handle', models.CharField(blank=True, max_length=100, null=True, verbose_name='Instagram Handle')),
                ('youtube_channel', models.URLField(blank=True, null=True, verbose_name='YouTube Channel')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Chicken Seller',
                'verbose_name_plural': 'Chicken Sellers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Consultant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('experience', models.PositiveIntegerField(help_text='Years of experience')),
                ('specialty', models.CharField(choices=[('disease', 'Disease Management'), ('nutrition', 'Nutrition & Feed'), ('prevention', 'Biosecurity & Prevention'), ('breeding', 'Breeding & Genetics'), ('general', 'General Practice')], max_length=20)),
                ('languages', models.CharField(help_text='Comma-separated list of languages', max_length=200)),
                ('rating', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)])),
                ('rating_count', models.PositiveIntegerField(default=0)),
                ('description', models.TextField()),
                ('availability', models.CharField(choices=[('weekdays', 'Weekdays'), ('weekends', 'Weekends'), ('all_week', 'All Week'), ('emergency', '24/7 Emergency')], max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('facebook', models.URLField(blank=True)),
                ('linkedin', models.URLField(blank=True)),
                ('whatsapp', models.CharField(blank=True, max_length=20)),
                ('is_available', models.BooleanField(default=True)),
                ('consultation_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
            ],
            options={
                'ordering': ['-rating'],
            },
        ),
        migrations.CreateModel(
            name='ConsultationBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=200)),
                ('user_email', models.EmailField(max_length=254)),
                ('user_phone', models.CharField(max_length=20)),
                ('preferred_date', models.DateField()),
                ('preferred_time', models.TimeField()),
                ('message', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ConsultationService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('video', 'Video Call'), ('phone', 'Phone Consultation'), ('visit', 'Farm Visit'), ('analysis', 'Feed Analysis'), ('assessment', 'Farm Assessment')], max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('duration', models.CharField(blank=True, help_text='e.g., 1 hour, per visit', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='EggOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=200)),
                ('customer_email', models.EmailField(max_length=254)),
                ('customer_phone', models.CharField(max_length=20)),
                ('customer_address', models.TextField()),
                ('quantity', models.PositiveIntegerField(help_text='Number of dozens ordered')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('special_instructions', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('processing', 'Processing'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('preferred_delivery_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EggSeller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farm_name', models.CharField(max_length=200)),
                ('owner_name', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(default='USA', max_length=100)),
                ('address', models.TextField(blank=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('egg_type', models.CharField(choices=[('organic', 'Organic'), ('free_range', 'Free Range'), ('cage_free', 'Cage Free'), ('conventional', 'Conventional'), ('pasture_raised', 'Pasture Raised')], default='conventional', max_length=20)),
                ('certification', models.CharField(choices=[('none', 'None'), ('usda_organic', 'USDA Organic'), ('non_gmo', 'Non-GMO Project Verified'), ('animal_welfare', 'Animal Welfare Approved'), ('local', 'Local Farm Certified')], default='none', max_length=20)),
                ('quantity_available', models.PositiveIntegerField(help_text='Number of eggs currently available')),
                ('price_per_dozen', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0)])),
                ('min_order_quantity', models.PositiveIntegerField(default=1, help_text='Minimum dozen required for order')),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('website', models.URLField(blank=True)),
                ('facebook', models.URLField(blank=True)),
                ('telegram', models.URLField(blank=True)),
                ('instagram', models.URLField(blank=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('rating', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)])),
                ('review_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Egg Seller',
                'verbose_name_plural': 'Egg Sellers',
                'ordering': ['-is_verified', '-rating'],
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=110, unique=True)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_featured', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('main_image', models.ImageField(blank=True, default='products/default.jpg', upload_to='products/main_images/')),
                ('like_count', models.PositiveIntegerField(default=0)),
                ('share_count', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='SubImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default='products/default.jpg', upload_to='products/sub_images/')),
                ('alt_text', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TrainingEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('program', models.CharField(choices=[('meat_chickens', 'Meat Chickens'), ('layer_chickens', 'Layer Chickens'), ('dual_purpose_chickens', 'Dual Purpose Chickens')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
