# Generated by Django 5.2.1 on 2025-09-22 13:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('poultryitems', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chickenseller',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='chicken_seller', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='consultationbooking',
            name='consultant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poultryitems.consultant'),
        ),
        migrations.AddField(
            model_name='consultationservice',
            name='consultant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='poultryitems.consultant'),
        ),
        migrations.AddField(
            model_name='consultationbooking',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poultryitems.consultationservice'),
        ),
        migrations.AddField(
            model_name='eggseller',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='egg_seller', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='eggorder',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='poultryitems.eggseller'),
        ),
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='poultryitems.category'),
        ),
        migrations.AddField(
            model_name='item',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='item',
            name='liked_by',
            field=models.ManyToManyField(blank=True, related_name='liked_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subimage',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_images', to='poultryitems.item'),
        ),
    ]
