# Generated by Django 5.2.1 on 2025-09-24 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poultryitems', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eggorder',
            name='total_price',
            field=models.DecimalField(decimal_places=3, max_digits=18),
        ),
    ]
