# Generated by Django 5.2.1 on 2025-09-21 13:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poultryitems', '0006_trainingenrollment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='liked_by',
            field=models.ManyToManyField(blank=True, related_name='liked_items', to=settings.AUTH_USER_MODEL),
        ),
    ]
